title: "Learning Stacks LLC"
tagline: "Online Learning Technology"
description: Learning Stacks provides Online Learning Technology services including Instructional Design, Multimedia production, and LMS customizations.

# url: https://www.learningstacks.com

source: .
destination: "./_site"
repository: learningstacks/learningstacks.github.io
github: [metadata]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - package.json
  - yarn.lock
  - update_bootstrap.sh
  - yarn-error.log
  - CNAME
  - docker-compose.yml
  - .env
  - .devcontainer

collections:
  - members
  - clients
  - capabilities

sass:
  style: compressed

plugins:
  - jekyll-seo-tag

show_dir_listing: false