destination: "_site"

keep_files:
  - _site

include:
  - .nojekyll

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh

collections:
  - members
  - clients
  - capabilities

sass:
  style: compressed