title: "Learning Stacks LLC"
tagline: "Online Learning Technology"
description: Learning Stacks provides Online Learning Technology services including Instructional Design, Multimedia production, and LMS customizations.

url: https://www.learningstacks.com

destination: "_site"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - package.json
  - yarn.lock
  - update_bootstrap.sh
  - yarn-error.log
  - CNAME

collections:
  - members
  - clients
  - capabilities

sass:
  style: compressed

plugins:
  - jekyll-seo-tag