destination: "_site"

keep_files:
  - _site

include:
  - .nojekyll

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - package.json
  - yarn.lock
  - update_bootstrap.sh
  - yarn-error.log
  - CNAME

collections:
  - members
  - clients
  - capabilities

sass:
  style: compressed